#!/bin/sh
TMP="$(dirname $(mktemp -u))/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.pnbpnusage"
TESTOCC="0"
cat > ${TESTFILE} << EOF
SRC_URI = "file://\${BPN}.patch \
           git://\${BPN}.com/\${BPN}.git \
           https://foo.org/\${BPN} \
           git://foo.org/bar.git;name=\${PN}"
SRC_URI = "\
    git://foo.org/baz.git;name=\${PN}-super \
    git://foo.org/\${BPN}.git;name=\${PN}-ultra \
"
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1