#!/bin/sh
TMP="$1/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
TESTPATCHFOLDER="/tmp"
trap "rm -f ${TESTFILE} && rm ${TESTPATCHFOLDER}/abc.inc" EXIT
TESTID="oelint.var.multiinclude"
TESTOCC="0"
cat > ${TESTFILE} << EOF
include abc.inc
B = "2"
EOF
mkdir -p ${TESTPATCHFOLDER}
cat > ${TESTPATCHFOLDER}/abc.inc << EOF
A = "1"
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1