#!/bin/sh
TMP="$(dirname $(mktemp -u))/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.var.licenseremotefile"
TESTOCC="1"
cat > ${TESTFILE} << EOF
LIC_FILES_CHKSUM = "file://\${COMMON_LIC_DIR}/MIT;md5=sjdjasdjhddh"
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1