#!/bin/sh
TMP="$(dirname $(mktemp -u))/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.valuequoted"
TESTOCC="2"
cat > ${TESTFILE} << EOF
A = "a
D = a"
E="b"
F+="c"
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1