#!/bin/sh
TMP="$1/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.srcurichecksum"
TESTOCC="1"
cat > ${TESTFILE} << EOF
SRC_URI += "ftp://foo"
SRC_URI += "ftp://foo"
SRC_URI += "http://foo;name=f1"
SRC_URI += "https://foo;name=f2"
SRC_URI[f1.md5sum] = "a"
SRC_URI[f1.sha256sum] = "a"
SRC_URI[f2.md5sum] = "a"
SRC_URI[f2.sha256sum] = "a"
SRC_URI[md5sum] = "a"
SRC_URI[sha256sum] = "a"
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1
