#!/bin/sh
TMP="$(dirname $(mktemp -u))/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.pkgspecific.*"
TESTOCC="0"
cat > ${TESTFILE} << EOF
RDEPENDS_\${PN} = "foo"
RRECOMMENDS_\${PN} = "foo"
RSUGGESTS_\${PN} = "foo"
RCONFLICTS_\${PN} = "foo"
RPROVIDES_\${PN} = "foo"
RREPLACES_\${PN} = "foo"
FILES_\${PN} = "foo"
pkg_preinst_\${PN} = "foo"
pkg_postinst_\${PN} = "foo"
pkg_prerm_\${PN} = "foo"
pkg_postrm_\${PN} = "foo"
ALLOW_EMPTY_\${PN} = "foo"
PACKAGES += "abc-foo"
RDEPENDS_abc-foo += "bar"
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1