#!/bin/sh
TMP="$(dirname $(mktemp -u))/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
TESTFILEINC="${TMP}oelint_adv_test.inc"
trap "rm -f ${TESTFILE} && rm -f ${TESTFILEINC}" EXIT
TESTID="oelint.file.requirenotfound"
TESTOCC="0"
cat > ${TESTFILEINC} << EOF
VAR = "a"
EOF
cat > ${TESTFILE} << EOF
require oelint_adv_test.inc
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1