#!/bin/sh
TMP="$(dirname $(mktemp -u))/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.var.licenseremotefile"
TESTOCC="0"
cat > ${TESTFILE} << EOF
LIC_FILES_CHKSUM = "file://LICENSE;md5=sjdjasdjhddh"
LIC_FILES_CHKSUM = "file://${WORKDIR}/LICENSE;md5=sjdjasdjhddh"
LIC_FILES_CHKSUM = "file://${S}/LICENSE;md5=sjdjasdjhddh"
LIC_FILES_CHKSUM = "file://${B}/LICENSE;md5=sjdjasdjhddh"
LIC_FILES_CHKSUM = "file://${A}/LICENSE;md5=sjdjasdjhddh"
A = "${WORKDIR}"
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1