#!/bin/sh
TMP="$(dirname $(mktemp -u))/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
TESTPATCHFOLDER="${TMP}files"
trap "rm -f ${TESTFILE} && rm -rf ${TESTPATCHFOLDER}" EXIT
TESTID="oelint.file.upstreamstatus"
TESTOCC="0"
cat > ${TESTFILE} << EOF
SRC_URI = "file://test.patch"
EOF
mkdir -p ${TESTPATCHFOLDER}
cat > ${TESTPATCHFOLDER}/test.patch << EOF
Upstream-Status: BOGUS
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1