#!/bin/sh
TMP="$1/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.srcurichecksum"
TESTOCC="0"
cat > ${TESTFILE} << EOF
SRC_URI += "file://foo"
SRC_URI += "bzr://foo"
SRC_URI += "crcc://foo"
SRC_URI += "cvs://foo"
SRC_URI += "ftp://foo;name=f3"
SRC_URI += "git://foo;name"
SRC_URI += "gitsm://foo"
SRC_URI += "gitannex://foo"
SRC_URI += "hg://foo"
SRC_URI += "http://foo;name=f1"
SRC_URI += "https://foo;name=f2"
SRC_URI += "osc://foo"
SRC_URI += "p4://foo"
SRC_URI += "repo://foo"
SRC_URI += "ssh://foo"
SRC_URI += "s3://foo;name=f5"
SRC_URI += "sftp://foo;name=f4"
SRC_URI += "npm://foo"
SRC_URI += "svn://foo"
SRC_URI[f1.md5sum] = "a"
SRC_URI[f1.sha256sum] = "a"
SRC_URI[f2.md5sum] = "a"
SRC_URI[f2.sha256sum] = "a"
SRC_URI[f3.md5sum] = "a"
SRC_URI[f3.sha256sum] = "a"
SRC_URI[f4.md5sum] = "a"
SRC_URI[f4.sha256sum] = "a"
SRC_URI[f5.md5sum] = "a"
SRC_URI[f5.sha256sum] = "a"
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1
