#!/bin/sh
TMP="$(dirname $(mktemp -u))/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.doublemodify"
TESTOCC="9"
cat > ${TESTFILE} << EOF
A_append_prepend_remove += "1"
A_append_prepend += "1"
A_append += "1"
A_prepend_remove += "1"
A_append_remove += "1"
A_remove += "1"
A_append_prepend_remove = " 1 "
A_append_remove = " 1 "
A_prepend_remove = " 1 "
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1