#!/bin/sh
TMP="$(dirname $(mktemp -u))/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.vars.pbpusage"
TESTOCC="0"
cat > ${TESTFILE} << EOF
SRC_URI = "file://\${BP}.patch \
           git://\${BP}.com/\${BP}.git \
           https://foo.org/\${BP} \
           git://foo.org/bar.git;name=\${P}"
SRCREV_${P} = "01234567890abcdef"
S = "${WORDKIR}/${BP}"
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1