#!/bin/sh
TMP="$1/"
TOOL="recipetool check"
TESTFILE="${TMP}oelint_adv_test.bb"
trap "rm -f ${TESTFILE}" EXIT
TESTID="oelint.append.protvars.*"
TESTOCC="0"
cat > ${TESTFILE} << EOF
PV = "sdlsdsd"
PR = "sdsd"
SRCREV = "ksdhdhkdhk"
LICENSE = "CLOSED"
LIC_FILES_CHKSUM = "skddskda"
EOF
[ $(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l) = "${TESTOCC}" ] && exit 0;
${TOOL} ${TESTFILE} 2>&1
_got=$(${TOOL} ${TESTFILE} 2>&1 | grep ":${TESTID}:" | wc -l)
echo "Test for ${0} failed - got ${_got} expected ${TESTOCC}"
exit 1